package org.apache.jsp.WEB_002dINF.view.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class frame_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();    
//获得项目完全路径（假设你的项目叫MyApp，那么获得到的地址就是 http://localhost:8080/MyApp/）:    
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path; 

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>CMS管理系统-生产环境-1.0</title>\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.print(basePath );
      out.write("/assets/ext-3.4.0/resources/css/ext-all.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/assets/ext-3.4.0/adapter/ext/ext-base.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/assets/ext-3.4.0/ext-all.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(basePath );
      out.write("/assets/ext-3.4.0/src/locale/ext-lang-zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\tExt.BLANK_IMAGE_URL = '");
      out.print(basePath );
      out.write("/assets/ext-3.4.0/resources/images/default/s.gif' ;\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"if(document.images) new Image().src= Ext.BLANK_IMAGE_URL;\"\r\n");
      out.write("\tonclick=\"if(window.self != window.top &&window.top&&window.top.Ext) window.top.Ext.menu.MenuMgr.hideAll();\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\tExt.onReady(function(){\r\n");
      out.write("\t\t\tExt.QuickTips.init();\r\n");
      out.write("\t\t\tExt.state.Manager.setProvider(new Ext.state.CookieProvider({\r\n");
      out.write("\t\t\t\texpires:null\r\n");
      out.write("\t\t\t\t}));\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar menu_user = {id:\"user\",text:\"用户管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/user/main', '用户管理', '');}};\r\n");
      out.write("\r\n");
      out.write("\t\tvar menu_role = {id:\"role\",text:\"角色管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/role/main', '角色管理', '');}};\r\n");
      out.write("\r\n");
      out.write("\t\tvar menu_config = {id:\"config\",text:\"系统参数配置\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/config/main', '系统参数配置', '');}};\r\n");
      out.write("\r\n");
      out.write("\t\tvar menu_sysManager = {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid:\"sysManager\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttext:\"系统管理\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\thandler:function(item){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\treturn;openMenu(item, '..', '系统管理', '');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t,menu: new Ext.menu.Menu({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\titems: [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tmenu_user\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t,menu_role\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t,menu_config\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\tvar menu_category = {id:\"category\",text:\"类别管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/category/main', '类别管理', '');}};\r\n");
      out.write("\r\n");
      out.write("\t\tvar menu_brand = {id:\"brand\",text:\"品牌管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/brand/main', '品牌管理', '');}};\r\n");
      out.write("\r\n");
      out.write("\t\tvar menu_baseProduct = {id:\"baseProduct\",text:\"产品管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/baseProduct/main', '产品管理', '');}};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar menu_shippingOption = {id:\"shippingOption\",text:\"物流管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/shippingOption/main', '物流管理', '');}};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar menu_country = {id:\"country\",text:\"国家代码管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/country/main', '国家代码管理', '');}};\r\n");
      out.write("\r\n");
      out.write("\t\tvar menu_dictionary = {id:\"dictionary\",text:\"数据字典管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/dictionary/main', '数据字典管理', '');}};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar menu_baseData = {\r\n");
      out.write("\t\t\t\t\t\t\tid:\"baseData\",\r\n");
      out.write("\t\t\t\t\t\t\ttext:\"基础数据\",\r\n");
      out.write("\t\t\t\t\t\t\thandler:function(item){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\treturn;openMenu(item, '..', '基础数据', '');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t,menu: new Ext.menu.Menu({\r\n");
      out.write("\t\t\t\t\t\t\t\titems: [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmenu_category\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t,menu_brand\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t,menu_baseProduct\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t,menu_shippingOption\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t,menu_country\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t,menu_dictionary\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar menu_member = {id:\"member\",text:\"会员管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/member/main', '会员管理', '');}};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar menu_guest = {id:\"guest\",text:\"游客管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/guest/main', '游客管理', '');}};\r\n");
      out.write("\r\n");
      out.write("\t\tvar menu_contact = {id:\"contact\",text:\"留言信息管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/contact/main', '留言信息管理', '');}};\r\n");
      out.write("\t\r\n");
      out.write("\t\tvar menu_task = {id:\"task\",text:\"定时器管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/task/main', '定时器管理', '');}};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar menu_taskEmail = {id:\"taskEmail\",text:\"目标客户\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/taskEmail/main', '目标客户', '');}};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar menu_bizData = {\r\n");
      out.write("\t\t\t\t\t\t\tid:\"bizData\",\r\n");
      out.write("\t\t\t\t\t\t\ttext:\"业务数据\",\r\n");
      out.write("\t\t\t\t\t\t\thandler:function(item){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\treturn;openMenu(item, '..', '业务数据', '');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t,menu: new Ext.menu.Menu({\r\n");
      out.write("\t\t\t\t\t\t\t\titems: [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmenu_member\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t,menu_guest\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t,menu_contact\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t,menu_task\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t,menu_taskEmail\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar menu_order = {id:\"order\",text:\"订单查询\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/order/main', '订单管理', '');}};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar menu_orderDetail = {id:\"orderDetail\",text:\"订单详情查询\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/orderDetail/main', '订单详情管理', '');}};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar menu_shopItem = {id:\"shopItem\",text:\"购物车管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/shopItem/main', '购物车管理', '');}};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar menu_awaitingPayOrder = {id:\"awaitingPayOrder\",text:\"未付款订单\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/order/awaitingPayOrder', '未付款订单', '');}};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar menu_prepareSendOrder = {id:\"prepareSendOrder\",text:\"待发货订单\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/order/prepareSendOrder', '待发货订单', '');}};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar menu_sendOrder = {id:\"sendOrder\",text:\"已发货订单\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/order/sendOrder', '已发货订单', '');}};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar menu_completedOrder = {id:\"completedOrder\",text:\"已完成订单\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/order/completedOrder', '已完成订单', '');}};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar menu_cancelledOrder = {id:\"cancelledOrder\",text:\"已取消订单\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/order/cancelledOrder', '已取消订单', '');}};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar menu_refundApplyOrder = {id:\"refundApplyOrder\",text:\"申请退款订单\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/order/refundApplyOrder', '申请退款订单', '');}};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar menu_auditedOrder = {id:\"auditedOrder\",text:\"退款审核通过订单\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/order/auditedOrder', '退款审核通过订单', '');}};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar menu_refundedOrder = {id:\"refundedOrder\",text:\"已退款订单\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/order/refundedOrder', '已退款订单', '');}};\r\n");
      out.write("\r\n");
      out.write("\t\tvar menu_declinedOrder = {id:\"declinedOrder\",text:\"拒绝退款订单\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/order/declinedOrder', '拒绝退款订单', '');}};\r\n");
      out.write("\r\n");
      out.write("\t\tvar menu_orderManager = {\r\n");
      out.write("\t\t\t\tid:\"orderManager\",\r\n");
      out.write("\t\t\t\ttext:\"订单管理\",\r\n");
      out.write("\t\t\t\thandler:function(item){\r\n");
      out.write("\t\t\t\t\t\t\t\t\treturn;openMenu(item, '..', '订单管理', '');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t,menu: new Ext.menu.Menu({\r\n");
      out.write("\t\t\t\t\titems: [\r\n");
      out.write("\t\t\t\t\t\t\tmenu_order\r\n");
      out.write("\t\t\t\t\t\t\t,menu_orderDetail\r\n");
      out.write("\t\t\t\t\t\t\t,menu_shopItem\r\n");
      out.write("\t\t\t\t\t\t\t,menu_awaitingPayOrder\r\n");
      out.write("\t\t\t\t\t\t\t,menu_prepareSendOrder\r\n");
      out.write("\t\t\t\t\t\t\t,menu_sendOrder\r\n");
      out.write("\t\t\t\t\t\t\t,menu_completedOrder\r\n");
      out.write("\t\t\t\t\t\t\t,menu_cancelledOrder\r\n");
      out.write("\t\t\t\t\t\t\t,menu_refundApplyOrder\r\n");
      out.write("\t\t\t\t\t\t\t,menu_auditedOrder\r\n");
      out.write("\t\t\t\t\t\t\t,menu_refundedOrder\r\n");
      out.write("\t\t\t\t\t\t\t,menu_declinedOrder\r\n");
      out.write("\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t//var menu_people2 = {id:\"people2\",text:\"人员管理\",handler:function(item){openMenu(item, '../../sys/emp_forward.action', '人员管理', '');}};\r\n");
      out.write("\r\n");
      out.write("\t\tvar menu_reportData = {\r\n");
      out.write("\t\t\t\t\t\t\tid:\"reportData\",\r\n");
      out.write("\t\t\t\t\t\t\ttext:\"报表管理\",\r\n");
      out.write("\t\t\t\t\t\t\thandler:function(item){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\treturn;openMenu(item, '..', '报表管理', '');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t,menu: new Ext.menu.Menu({\r\n");
      out.write("\t\t\t\t\t\t\t\titems: [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//menu_people2\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\tvar menuBar = new Ext.Toolbar({\r\n");
      out.write("\t\t\t\t\t\t\tenableOverflow:\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t,items: [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t'-'\t,menu_sysManager,'-',menu_baseData,'-',menu_bizData,'-',menu_orderManager,'-',menu_reportData,'-','->'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t,{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ticon:\"");
      out.print(basePath );
      out.write("/assets/images/frame/new.gif\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttext:\"工具\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tcls:\"x-btn-text-icon\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t,menu: new Ext.menu.Menu({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tshowSeparator:\"false\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t,items: [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ticon:\"");
      out.print(basePath );
      out.write("/assets/images/frame/home.gif\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttext:\"返回首页\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcls:\"x-btn-text-icon\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttabs.setActiveTab('home');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ticon:\"");
      out.print(basePath );
      out.write("/assets/images/frame/close.gif\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttext:\"关闭所有标签页\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcls:\"x-btn-text-icon\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcloseAllTab();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ticon:\"");
      out.print(basePath );
      out.write("/assets/images/frame/version.gif\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttext:\"版本信息\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcls:\"x-btn-text-icon\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tversionWin.show();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ticon:\"");
      out.print(basePath );
      out.write("/assets/images/frame/user.gif\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttext:\"用户信息\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcls:\"x-btn-text-icon\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tuserWin.show();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ticon:\"");
      out.print(basePath );
      out.write("/assets/images/frame/password.gif\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttext:\"修改密码\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcls:\"x-btn-text-icon\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tchangePasswordWin.show();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ticon:\"");
      out.print(basePath );
      out.write("/assets/images/frame/exit.gif\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttext:\"退出登录\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcls:\"x-btn-text-icon\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thandler:function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tlogout();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t' '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar tabs = new Ext.TabPanel({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tregion:\"center\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tautoScroll:true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tactiveItem:\"home\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tborder:false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tenableTabScroll:true\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t,items: [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tnew Ext.Panel({id:\"home\",title:\"首页\",layout:\"border\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,items: [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tnew Ext.Panel({id:\"homemain\",region:\"center\",border:false\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,html: \"\\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t<iframe src=\\'");
      out.print(basePath);
      out.write("/home\\' width=\\'100%\\' height=\\'100%\\' frameborder=\\'0\\'></iframe>\\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\"\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,new Ext.Panel({id:\"homebar\",region:\"north\",cls:\"x-toolbar\",height:25,layout:\"border\",border:false\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,items: [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tnew Ext.Panel({id:\"homemsg\",region:\"center\",border:false\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,html: \"\\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t<table border=\\'0\\' cellpadding=\\'0\\' cellspacing=\\'0\\' width=\\'100%\\' height=\\\"25\\\" style=\\'background-color: #FFDF8C;\\'><tr><td width=\\'24\\' align=\\'center\\'><img src=\\'");
      out.print(basePath );
      out.write("/assets/images/frame/info.gif\\' border=\\'0\\' height=\\'16\\' width=\\'16\\'/></td><td>XX管理系统demo</td></tr></table>\\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,new Ext.Panel({id:\"homebtn\",region:\"east\",width:22,border:false\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,items: [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tnew Ext.Button({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid:\"homehelp\",icon:\"");
      out.print(basePath );
      out.write("/assets/images/frame/help.gif\",cls:\"x-btn-icon\",style:\"background-color: #FFDF8C;\",tooltip:\"帮助\",handler:function() {showHelp('');}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar framePane = new Ext.Viewport({\r\n");
      out.write("\t\t\t\t\t\t\tlayout:\"border\"\r\n");
      out.write("\t\t\t\t\t\t\t,items: [\r\n");
      out.write("\t\t\t\t\t\t\t\t\tnew Ext.Panel({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttbar:menuBar,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tregion:\"center\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tlayout:\"border\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tborder:false\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t,items: [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttabs\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar userWin = new Ext.Window({\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle:\"用户信息\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\theight:200,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tframe:true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth:300,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlayout:\"border\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcloseAction:\"hide\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmodal:true\r\n");
      out.write("\t\t\t\t\t\t\t\t\t,items: [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tnew Ext.Panel({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tregion:\"center\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tframe:true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tborder:false\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,html:\"\\r\\n\\t\\t\\t\\t\\t<table border=\\\"0\\\" width=\\\"100%\\\" class=\\\"x-form-field\\\" style=\\\"font-size:15\\\">\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"\\r\\n\\t\\t\\t\\t\\t\\t<tr>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td colspan=\\\"2\\\">&nbsp;</td>\\r\\n\\t\\t\\t\\t\\t\\t</tr>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"\\r\\n\\t\\t\\t\\t\\t\\t<tr>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td style=\\\"border-bottom:1px dashed #BEBEBE\\\" align=\\\"right\\\" width=\\\"120\\\">用户名&nbsp;:&nbsp;&nbsp;</td>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"\\r\\n\\t\\t\\t\\t\\t\\t\\t<td style=\\\"border-bottom:1px dashed #BEBEBE\\\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userName}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("</td>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"\\r\\n\\t\\t\\t\\t\\t\\t\\r\\n\\t\\t\\t\\t\\t</table>\\r\\n\\t\\t\\t\\t\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar versionWin = new Ext.Window({\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle:\"版本信息\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\theight:330,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tframe:true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth:345,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlayout:\"border\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcloseAction:\"hide\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmodal:true\r\n");
      out.write("\t\t\t\t\t\t\t\t\t,items: [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tnew Ext.Panel({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tregion:\"center\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tframe:true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tborder:false\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t,html:\"\\r\\n\\t\\t\\t\\t\\t<table border=\\\"0\\\" class=\\\"x-form-field\\\" style=\\\"font-size:14\\\">\\r\\n\\t\\t\\t\\t\\t\\t<tr>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td colspan=\\\"2\\\"><a href=\\\"http://www.sf-express.com\\\" target=\\\"_blank\\\"><img style=\\\"background-color: black\\\" src=\\\"");
      out.print(basePath );
      out.write("/assets/images/frame/sf_logo.png\\\" alt=\\\"SF-Express\\\"/></a></td>\\r\\n\\t\\t\\t\\t\\t\\t</tr>\\r\\n\\t\\t\\t\\t\\t\\t<tr>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td colspan=\\\"2\\\" style=\\\"font-size:20\\\">XX管理系统demo</td>\\r\\n\\t\\t\\t\\t\\t\\t</tr>\\r\\n\\t\\t\\t\\t\\t\\t<tr>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td colspan=\\\"2\\\"><hr/></td>\\r\\n\\t\\t\\t\\t\\t\\t</tr>\\r\\n\\t\\t\\t\\t\\t\\t<tr>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td align=\\\"right\\\" width=\\\"120\\\">版本类型&nbsp;:&nbsp;&nbsp;</td>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td>生产环境(product)</td>\\r\\n\\t\\t\\t\\t\\t\\t</tr>\\r\\n\\t\\t\\t\\t\\t\\t<tr>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td align=\\\"right\\\">版本号&nbsp;:&nbsp;&nbsp;</td>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td>1.0</td>\\r\\n\\t\\t\\t\\t\\t\\t</tr>\\r\\n\\t\\t\\t\\t\\t\\t<tr>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td align=\\\"right\\\">发布时间&nbsp;:&nbsp;&nbsp;</td>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td>@release.date@</td>\\r\\n\\t\\t\\t\\t\\t\\t</tr>\\r\\n\\t\\t\\t\\t\\t\\t<tr>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td align=\\\"right\\\">Framework&nbsp;:&nbsp;&nbsp;</td>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td>EXT3-MIXROLE</td>\\r\\n\\t\\t\\t\\t\\t\\t</tr>\\t\\t\\t\\t\\t\\t\\r\\n\\t\\t\\t\\t\\t\\t<tr>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td colspan=\\\"2\\\"><hr/></td>\\r\\n\\t\\t\\t\\t\\t\\t</tr>\\r\\n\\t\\t\\t\\t\\t\\t<tr>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td colspan=\\\"2\\\">Copyright (c) 2012, S.F. Express Inc. All rights reserved.</td>\\r\\n\\t\\t\\t\\t\\t\\t</tr>\\r\\n\\t\\t\\t\\t\\t\\t<tr>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td colspan=\\\"2\\\"><br/></td>\\r\\n\\t\\t\\t\\t\\t\\t</tr>\\r\\n\\t\\t\\t\\t\\t</table>\\r\\n\\t\\t\\t\\t\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar oldPasswordVar = new Ext.form.TextField({minLengthText:\"旧密码最小长度为8\",allowBlank:false,maxLength:20,blankText:\"旧密码不能为空\",minLength:6,inputType:\"password\",name:\"oldPassword\",maxLengthText:\"旧密码最大长度为20\",fieldLabel:\"旧密码\"});\r\n");
      out.write("\r\n");
      out.write("\t\tvar newPasswordVar = new Ext.form.TextField({minLengthText:\"新密码最小长度为8\",allowBlank:false,maxLength:20,blankText:\"新密码不能为空\",minLength:6,inputType:\"password\",name:\"newPassword\",maxLengthText:\"新密码最大长度为20\",fieldLabel:\"新密码\"});\r\n");
      out.write("\r\n");
      out.write("\t\tvar newPasswordConfirmVar = new Ext.form.TextField({minLengthText:\"确认新密码最小长度为8\",allowBlank:false,maxLength:20,blankText:\"确认新密码不能为空\",minLength:6,inputType:\"password\",name:\"newPasswordConfirm\",maxLengthText:\"确认新密码最大长度为20\",fieldLabel:\"确认新密码\"});\r\n");
      out.write("\r\n");
      out.write("\t\tvar changePasswordForm = new Ext.form.FormPanel({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tregion:\"center\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tframe:true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tborder:false\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t,items: [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\toldPasswordVar\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t,newPasswordVar\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t,newPasswordConfirmVar\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar changePasswordWin = new Ext.Window({\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle:\"修改密码\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\theight:240,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tframe:true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth:300,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlayout:\"border\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcloseAction:\"hide\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmodal:true\r\n");
      out.write("\t\t\t\t\t\t\t\t\t,items: [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tnew Ext.Panel({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tregion:\"center\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tlayout:\"border\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tborder:false\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t,tbar: [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tnew Ext.Button({text:\"保存\",cls:\"x-btn-normal\",handler:saveChangePwd\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,new Ext.Button({text:\"重置\",cls:\"x-btn-normal\",handler:function() {changePasswordForm.getForm().reset();}\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t,items: [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tchangePasswordForm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\tchangePasswordForm.savePassword = function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tchangePasswordForm.getForm().doAction(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'submit',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfailure:changePasswordFailure,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsuccess:changePasswordSuccess,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\turl:\"");
      out.print(basePath );
      out.write("/user/changPassword\"});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t    function saveChangePwd() {\r\n");
      out.write("\t\t\t\t\t\tif(changePasswordForm.getForm().isValid()) {\r\n");
      out.write("\t\t\t\t\t\t\tvar oldPasswordVarValue = oldPasswordVar.getValue();\r\n");
      out.write("\t\t\t\t\t\t\tvar newPasswordVarValue = newPasswordVar.getValue();\r\n");
      out.write("\t\t\t\t\t\t\tvar newPasswordConfirmVarValue = newPasswordConfirmVar.getValue();\r\n");
      out.write("\t\t\t\t\t\t\tif (validatePassword(oldPasswordVarValue, newPasswordVarValue, newPasswordConfirmVarValue))\r\n");
      out.write("\t\t\t\t\t\t\t\tchangePasswordForm.savePassword();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 检验密码表单数据\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction validatePassword(oldPasswordVarValue, newPasswordVarValue, newPasswordConfirmVarValue) {\r\n");
      out.write("\t\t\t\tif(! checkPassword(oldPasswordVarValue, '旧密码')) {\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(! checkPassword(newPasswordVarValue, '新密码')) {\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(! checkPassword(newPasswordConfirmVarValue, '确认新密码')) {\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(oldPasswordVarValue == newPasswordVarValue){\r\n");
      out.write("\t\t\t\t\tExt.MessageBox.alert('提示', '新密码不能与旧密码相同!');\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(newPasswordVarValue != newPasswordConfirmVarValue) {\r\n");
      out.write("\t\t\t\t\tExt.MessageBox.alert('提示', '确认新密码与新密码不一致!');\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 检验密码，包括长度为八位，必需为数字与字母混合等\r\n");
      out.write("\t\t\tfunction checkPassword(password, name) {\r\n");
      out.write("\t\t\t    if(password == null || password == ''){\r\n");
      out.write("\t\t\t        Ext.MessageBox.alert('提示', name + '不能为空');\r\n");
      out.write("\t\t\t        return false;\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t    if(password.length < 8){\r\n");
      out.write("\t\t\t        Ext.MessageBox.alert('提示', name + '长度必须大于八位');\r\n");
      out.write("\t\t\t        return false;\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t        var pwdPtn = /^[\\x21-\\x7e]*$/;\r\n");
      out.write("\t\t       \tif(!pwdPtn.test(password)){\r\n");
      out.write("\t\t       \t    Ext.MessageBox.alert('提示', name + '必须由英文字母、数字和特殊字符组成，必须同时包含字母和数字');\r\n");
      out.write("\t\t       \t    return false;\r\n");
      out.write("\t\t       \t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t    //判断是否数字和英文组成\r\n");
      out.write("\t\t\t    var numFlag = false;\r\n");
      out.write("\t\t\t    var charFlag = false;\r\n");
      out.write("\t\t\t    for(var i =0; i < password.length; i++){\r\n");
      out.write("\t\t\t        if(password.charAt(i) >= '0' && password.charAt(i) <= '9'){\r\n");
      out.write("\t\t\t            numFlag = true;\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t        if( ( password.charAt(i) >= 'A' && password.charAt(i) <= 'Z' ) || ( password.charAt(i) >= 'a' && password.charAt(i) <= 'z' )){\r\n");
      out.write("\t\t\t            charFlag = true;\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t    if(! charFlag || ! numFlag ) {\r\n");
      out.write("\t\t\t        Ext.MessageBox.alert('提示', name + '必须由英文字母、数字和特殊字符组成，必须同时包含字母和数字');\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t    return true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction changePasswordSuccess(form, action) {\r\n");
      out.write("\t\t\t\tif (action.result.msg) {\r\n");
      out.write("\t\t\t\t\tExt.Msg.alert(\"提示\",action.result.msg);\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tchangePasswordWin.hide();\r\n");
      out.write("\t\t\t\t\tchangePasswordForm.getForm().reset();\r\n");
      out.write("\t\t\t\t\tExt.MessageBox.alert(\"成功\", \"修改密码成功,将在您下一次登录时生效!\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction changePasswordFailure(form, action) {\r\n");
      out.write("\t\t\t\tvar msg = '';\r\n");
      out.write("\t\t\t\tif (action && action.result && action.result.error) {\r\n");
      out.write("\t\t\t\t\tExt.Msg.alert(\"提示\",\"系统出现了异常,请与管理员联系!\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tif (action.failureType === Ext.form.Action.CONNECT_FAILURE) {\r\n");
      out.write("\t\t\t\t\t\tif (action.response.status == 0) {\r\n");
      out.write("\t\t\t\t\t\t\tmsg = \"连接失败,无法连接到服务器!\";\r\n");
      out.write("\t\t\t\t\t\t} else if (action.response.status == -1) {\r\n");
      out.write("\t\t\t\t\t\t\tmsg = \"服务器处理超时!\";\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tmsg = String.format(\"错误代码:{0}, 错误描述:{1}!\",action.response.status,action.response.statusText);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t} else if (action.failureType === Ext.form.Action.CLIENT_INVALID) {\r\n");
      out.write("\t\t\t\t\t\tmsg = \"请将表单填写正确!\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tExt.Msg.alert(\"提示\", msg);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t    function closeAllTab() {\r\n");
      out.write("\t\t        var ts = tabs.findBy(function() {\r\n");
      out.write("\t\t            if (this.id != 'home' \r\n");
      out.write("\t\t                && this.id != 'homemain' \r\n");
      out.write("\t\t                && this.id != 'homemain' \r\n");
      out.write("\t\t                && this.id != 'homebar' \r\n");
      out.write("\t\t                && this.id != 'homemsg'\r\n");
      out.write("\t\t                && this.id != 'homebtn' \r\n");
      out.write("\t\t                && this.id != 'homehelp') {\r\n");
      out.write("\t\t                return true;\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t        });\r\n");
      out.write("\r\n");
      out.write("\t\t        for (i = 0; i < ts.length; i++) {\r\n");
      out.write("\t\t            tabs.remove(ts[i]);\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction showHelp(helpUrl) {\r\n");
      out.write("\t\t\t\tif (helpUrl && helpUrl.length > 0) {\r\n");
      out.write("\t\t\t\t\twindow.open('' + helpUrl, '_blank', 'height=600,width=800,resizable=yes,scrollbars=yes');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction logoutConfirmed(s) {\r\n");
      out.write("\t\t\t\tif (s == 'yes') {\r\n");
      out.write("\t\t\t\t\twindow.location.href='");
      out.print(basePath );
      out.write("/login/logout';\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction logout() {\r\n");
      out.write("\t\t\t\tExt.MessageBox.confirm(\"退出登录\", \"确定退出登录?&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\", logoutConfirmed);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction openMenu(item, url, desc, helpUrl) {\r\n");
      out.write("\t\t\t    if(url != null && url != ''){\r\n");
      out.write("\t\t\t\t\topenPage(item.id, item.text, desc, helpUrl, url, true);\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction openTab(id, text, desc, helpUrl, url) {\r\n");
      out.write("\t\t\t\tif(url != null && url != ''){\r\n");
      out.write("\t\t\t\t\topenPage(id, text, desc, helpUrl, url, true);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction refreshTab(id, text, desc, helpUrl, url) {\r\n");
      out.write("\t\t\t\trefreshPage(id, text, desc, helpUrl, url, true);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction openPage(id, text, desc, helpUrl, url, closable) {\r\n");
      out.write("\t\t\t\tvar tab = tabs.getItem(id);\r\n");
      out.write("\t\t\t\tif (typeof(tab) == \"undefined\" || tab == null) {\r\n");
      out.write("\t\t\t\t\ttabs.add(createTabPane(id, text, desc, helpUrl, url, closable)).show();\r\n");
      out.write("\t\t        } else {\r\n");
      out.write("\t\t        \ttabs.setActiveTab(tab);\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction refreshPage(id, text, desc, helpUrl, url, closable) {\r\n");
      out.write("\t\t\t\tvar tab = tabs.getItem(id);\r\n");
      out.write("\t\t\t\tif (typeof(tab) != \"undefined\" && tab != null) {\r\n");
      out.write("\t\t\t\t\ttabs.remove(tab);\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t        tabs.add(createTabPane(id, text, desc, helpUrl, url, closable)).show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction createTabPane(id, text, desc, helpUrl, url, closable) {\r\n");
      out.write("\t\t\t\tvar tabPane = new Ext.Panel({\r\n");
      out.write("\t\t\t\t\t\tid: id,\r\n");
      out.write("\t\t\t\t\t\ttitle: text,\r\n");
      out.write("\t\t\t\t\t\tborder: false,\r\n");
      out.write("\t\t\t\t\t\tclosable: closable,\r\n");
      out.write("\t\t\t\t\t\tlayout: \"border\",\r\n");
      out.write("\t\t\t\t\t\titems: [\r\n");
      out.write("\t\t\t\t\t\t\tnew Ext.Panel({\r\n");
      out.write("\t\t\t\t\t\t\t\tregion: \"north\",\r\n");
      out.write("\t\t\t\t\t\t\t\tcls: \"x-toolbar\",\r\n");
      out.write("\t\t\t\t\t\t\t\theight: 25,\r\n");
      out.write("\t\t\t\t\t\t\t\tborder: false,\r\n");
      out.write("\t\t\t\t\t\t\t\tlayout: \"border\",\r\n");
      out.write("\t\t\t\t\t\t\t\titems: [\r\n");
      out.write("\t\t\t\t\t\t\t\t\tnew Ext.Panel({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tregion: \"east\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth: 44,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tborder: false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tlayout: \"border\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\titems: [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tnew Ext.Panel({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tregion: \"west\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\twidth: 22,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tborder: false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tlayout: \"form\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\titems: [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tnew Ext.Button({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tcls: \"x-btn-icon\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ticon: \"");
      out.print(basePath );
      out.write("/assets/images/frame/new.gif\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ttooltip: \"在新的标签页中打开\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle: \"background-color: #FFDF8C;\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\thandler: function(){openPage(id + '1', text, desc, helpUrl, url, closable);}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}),\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tnew Ext.Panel({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tregion: \"center\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tborder: false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tlayout: \"form\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\titems: [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tnew Ext.Button({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tcls: \"x-btn-icon\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ticon: \"");
      out.print(basePath );
      out.write("/assets/images/frame/help.gif\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ttooltip: \"帮助\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle: \"background-color: #FFDF8C;\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\thandler: function(){showHelp(helpUrl);}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}),\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\tnew Ext.Panel({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tregion: \"center\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tborder: false,\r\n");
      out.write("\t\t\t\t\t            \t\thtml: \"<table border='0' cellpadding='0' cellspacing='0' width='100%' height='25' style='background-color: #FFDF8C;'><tr><td width='24' align='center'><img src='");
      out.print(basePath );
      out.write("/assets/images/frame/info.gif' border='0' height='16' width='16'/></td><td>\" + desc + \"</td></tr></table>\"\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t        \t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t        }),\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t        new Ext.Panel({\r\n");
      out.write("\t\t\t\t\t\t\t\tregion: \"center\",\r\n");
      out.write("\t\t\t\t\t\t\t\tborder: false,\r\n");
      out.write("\t\t\t\t\t            html: \"<iframe name='frame_\" + id + \"' src='\" + url + \"' width='100%' height='100%' frameborder='0'></iframe>\"\r\n");
      out.write("\t\t\t\t\t        })\r\n");
      out.write("\t\t\t        \t]\r\n");
      out.write("\t\t\t        });\r\n");
      out.write("\t\t\t\treturn tabPane;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar mask = null;\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 传入的参数为不被遮罩的元素\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction showModal(win) {\r\n");
      out.write("\t\t\t\tif (mask == null) {\r\n");
      out.write("\t\t\t\t\tif (win && win.el && win.el.dom) {\r\n");
      out.write("\t\t\t\t\t\tmask = framePane.container.createChild({cls:\"ext-el-mask\"}, win.el.dom);\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tuserWin.show();\r\n");
      out.write("\t\t\t\t\t\tuserWin.hide();\r\n");
      out.write("\t\t\t\t\t\tmask = framePane.container.createChild({cls:\"ext-el-mask\"}, userWin.el.dom);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tExt.getBody().addClass(\"x-body-masked\");\r\n");
      out.write("\t\t\t\tmask.setSize(Ext.lib.Dom.getViewWidth(true), Ext.lib.Dom.getViewHeight(true));\r\n");
      out.write("\t\t\t\tmask.show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction hideModal() {\r\n");
      out.write("\t\t\t\tmask.hide();\r\n");
      out.write("\t\t\t\tExt.getBody().removeClass(\"x-body-masked\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction requestBlank() {\r\n");
      out.write("\t\t\t\tExt.Ajax.request({\r\n");
      out.write("\t\t\t\t\turl: 'blank.action',\r\n");
      out.write("\t\t\t\t\tmethod: 'GET',\r\n");
      out.write("\t\t\t\t\tdisableCaching: true,\r\n");
      out.write("\t\t\t\t\tsuccess: function (result, request) {\r\n");
      out.write("\t\t\t\t\t\tif (result.responseText.indexOf('okokokokokok') == -1) {\r\n");
      out.write("\t\t\t\t\t\t\twindow.location.href='logout.action';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\ttry{\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tsetInterval(\"requestBlank()\", 1801000);\r\n");
      out.write("\r\n");
      out.write("\t\t\t} catch(e) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("</script><style type=\"text/css\"></style>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
