package org.apache.jsp.WEB_002dINF.view.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class frame_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

String path = request.getContextPath();    
//获得项目完全路径（假设你的项目叫MyApp，那么获得到的地址就是 http://localhost:8080/MyApp/）:    
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path; 

      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>CMS管理系统-生产环境-1.0</title>\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">\n");
      out.write("<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\n");
      out.write("<meta http-equiv=\"description\" content=\"This is my page\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\thref=\"");
      out.print(basePath );
      out.write("/assets/ext-3.4.0/resources/css/ext-all.css\" />\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/assets/ext-3.4.0/adapter/ext/ext-base.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/assets/ext-3.4.0/ext-all.js\"></script>\n");
      out.write("<script type=\"text/javascript\"\n");
      out.write("\tsrc=\"");
      out.print(basePath );
      out.write("/assets/ext-3.4.0/src/locale/ext-lang-zh_CN.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t\tExt.BLANK_IMAGE_URL = '");
      out.print(basePath );
      out.write("/assets/ext-3.4.0/resources/images/default/s.gif' ;\n");
      out.write("\t</script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body onload=\"if(document.images) new Image().src= Ext.BLANK_IMAGE_URL;\"\n");
      out.write("\tonclick=\"if(window.self != window.top &&window.top&&window.top.Ext) window.top.Ext.menu.MenuMgr.hideAll();\">\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t\tExt.onReady(function(){\n");
      out.write("\t\t\tExt.QuickTips.init();\n");
      out.write("\t\t\tExt.state.Manager.setProvider(new Ext.state.CookieProvider({\n");
      out.write("\t\t\t\texpires:null\n");
      out.write("\t\t\t\t}));\n");
      out.write("\t\t\t});\n");
      out.write("\n");
      out.write("\t\tvar menu_user = {id:\"user\",text:\"用户管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/user/main', '用户管理', '');}};\n");
      out.write("\n");
      out.write("\t\tvar menu_role = {id:\"role\",text:\"角色管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/role/main', '角色管理', '');}};\n");
      out.write("\n");
      out.write("\t\tvar menu_config = {id:\"config\",text:\"系统参数配置\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/config/main', '系统参数配置', '');}};\n");
      out.write("\n");
      out.write("\t\tvar menu_sysManager = {\n");
      out.write("\t\t\t\t\t\t\t\t\tid:\"sysManager\",\n");
      out.write("\t\t\t\t\t\t\t\t\ttext:\"系统管理\",\n");
      out.write("\t\t\t\t\t\t\t\t\thandler:function(item){\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\treturn;openMenu(item, '..', '系统管理', '');\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t,menu: new Ext.menu.Menu({\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\titems: [\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tmenu_user\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t,menu_role\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t,menu_config\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t\t\t};\n");
      out.write("\n");
      out.write("\t\tvar menu_category = {id:\"category\",text:\"类别管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/category/main', '类别管理', '');}};\n");
      out.write("\n");
      out.write("\t\tvar menu_brand = {id:\"brand\",text:\"品牌管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/brand/main', '品牌管理', '');}};\n");
      out.write("\n");
      out.write("\t\tvar menu_baseProduct = {id:\"baseProduct\",text:\"产品管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/baseProduct/main', '产品管理', '');}};\n");
      out.write("\t\t\n");
      out.write("\t\tvar menu_shippingOption = {id:\"shippingOption\",text:\"物流管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/shippingOption/main', '物流管理', '');}};\n");
      out.write("\t\t\n");
      out.write("\t\tvar menu_country = {id:\"country\",text:\"国家代码管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/country/main', '国家代码管理', '');}};\n");
      out.write("\n");
      out.write("\t\tvar menu_dictionary = {id:\"dictionary\",text:\"数据字典管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/dictionary/main', '数据字典管理', '');}};\n");
      out.write("\t\t\n");
      out.write("\t\tvar menu_baseData = {\n");
      out.write("\t\t\t\t\t\t\tid:\"baseData\",\n");
      out.write("\t\t\t\t\t\t\ttext:\"基础数据\",\n");
      out.write("\t\t\t\t\t\t\thandler:function(item){\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\treturn;openMenu(item, '..', '基础数据', '');\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t,menu: new Ext.menu.Menu({\n");
      out.write("\t\t\t\t\t\t\t\titems: [\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmenu_category\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t,menu_brand\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t,menu_baseProduct\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t,menu_shippingOption\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t,menu_country\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t,menu_dictionary\n");
      out.write("\t\t\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t};\n");
      out.write("\t\t\n");
      out.write("\t\tvar menu_member = {id:\"member\",text:\"会员管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/member/main', '会员管理', '');}};\n");
      out.write("\t\t\n");
      out.write("\t\tvar menu_guest = {id:\"guest\",text:\"游客管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/guest/main', '游客管理', '');}};\n");
      out.write("\n");
      out.write("\t\tvar menu_contact = {id:\"contact\",text:\"留言信息管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/contact/main', '留言信息管理', '');}};\n");
      out.write("\t\n");
      out.write("\t\tvar menu_task = {id:\"task\",text:\"定时器管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/task/main', '定时器管理', '');}};\n");
      out.write("\t\t\n");
      out.write("\t\tvar menu_taskEmail = {id:\"taskEmail\",text:\"目标客户\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/taskEmail/main', '目标客户', '');}};\n");
      out.write("\t\t\n");
      out.write("\t\tvar menu_discode = {id:\"discode\",text:\"折扣码管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/discode/main', '折扣码管理', '');}};\n");
      out.write("\t\t\n");
      out.write("\t\tvar menu_bizData = {\n");
      out.write("\t\t\t\t\t\t\tid:\"bizData\",\n");
      out.write("\t\t\t\t\t\t\ttext:\"业务数据\",\n");
      out.write("\t\t\t\t\t\t\thandler:function(item){\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\treturn;openMenu(item, '..', '业务数据', '');\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t,menu: new Ext.menu.Menu({\n");
      out.write("\t\t\t\t\t\t\t\titems: [\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmenu_member\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t,menu_guest\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t,menu_contact\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t,menu_task\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t,menu_taskEmail\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t,menu_discode\n");
      out.write("\t\t\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t};\n");
      out.write("\t\t\n");
      out.write("\t\tvar menu_order = {id:\"order\",text:\"订单查询\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/order/main', '订单管理', '');}};\n");
      out.write("\t\t\n");
      out.write("\t\tvar menu_orderDetail = {id:\"orderDetail\",text:\"订单详情查询\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/orderDetail/main', '订单详情管理', '');}};\n");
      out.write("\t\t\n");
      out.write("\t\tvar menu_shopItem = {id:\"shopItem\",text:\"购物车管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/shopItem/main', '购物车管理', '');}};\n");
      out.write("\t\t\n");
      out.write("\t\tvar menu_awaitingPayOrder = {id:\"awaitingPayOrder\",text:\"未付款订单\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/order/awaitingPayOrder', '未付款订单', '');}};\n");
      out.write("\t\t\n");
      out.write("\t\tvar menu_prepareSendOrder = {id:\"prepareSendOrder\",text:\"待发货订单\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/order/prepareSendOrder', '待发货订单', '');}};\n");
      out.write("\t\t\n");
      out.write("\t\tvar menu_sendOrder = {id:\"sendOrder\",text:\"已发货订单\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/order/sendOrder', '已发货订单', '');}};\n");
      out.write("\t\t\n");
      out.write("\t\tvar menu_completedOrder = {id:\"completedOrder\",text:\"已完成订单\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/order/completedOrder', '已完成订单', '');}};\n");
      out.write("\t\t\n");
      out.write("\t\tvar menu_cancelledOrder = {id:\"cancelledOrder\",text:\"已取消订单\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/order/cancelledOrder', '已取消订单', '');}};\n");
      out.write("\t\t\n");
      out.write("\t\tvar menu_refundApplyOrder = {id:\"refundApplyOrder\",text:\"申请退款订单\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/order/refundApplyOrder', '申请退款订单', '');}};\n");
      out.write("\t\t\n");
      out.write("\t\tvar menu_auditedOrder = {id:\"auditedOrder\",text:\"退款审核通过订单\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/order/auditedOrder', '退款审核通过订单', '');}};\n");
      out.write("\t\t\n");
      out.write("\t\tvar menu_refundedOrder = {id:\"refundedOrder\",text:\"已退款订单\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/order/refundedOrder', '已退款订单', '');}};\n");
      out.write("\n");
      out.write("\t\tvar menu_declinedOrder = {id:\"declinedOrder\",text:\"拒绝退款订单\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/order/declinedOrder', '拒绝退款订单', '');}};\n");
      out.write("\n");
      out.write("\t\tvar menu_orderManager = {\n");
      out.write("\t\t\t\tid:\"orderManager\",\n");
      out.write("\t\t\t\ttext:\"订单管理\",\n");
      out.write("\t\t\t\thandler:function(item){\n");
      out.write("\t\t\t\t\t\t\t\t\treturn;openMenu(item, '..', '订单管理', '');\n");
      out.write("\t\t\t\t\t\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\t,menu: new Ext.menu.Menu({\n");
      out.write("\t\t\t\t\titems: [\n");
      out.write("\t\t\t\t\t\t\tmenu_order\n");
      out.write("\t\t\t\t\t\t\t,menu_orderDetail\n");
      out.write("\t\t\t\t\t\t\t,menu_shopItem\n");
      out.write("\t\t\t\t\t\t\t,menu_awaitingPayOrder\n");
      out.write("\t\t\t\t\t\t\t,menu_prepareSendOrder\n");
      out.write("\t\t\t\t\t\t\t,menu_sendOrder\n");
      out.write("\t\t\t\t\t\t\t,menu_completedOrder\n");
      out.write("\t\t\t\t\t\t\t,menu_cancelledOrder\n");
      out.write("\t\t\t\t\t\t\t,menu_refundApplyOrder\n");
      out.write("\t\t\t\t\t\t\t,menu_auditedOrder\n");
      out.write("\t\t\t\t\t\t\t,menu_refundedOrder\n");
      out.write("\t\t\t\t\t\t\t,menu_declinedOrder\n");
      out.write("\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t})\n");
      out.write("\t\t\t};\n");
      out.write("\n");
      out.write("\t\t//var menu_people2 = {id:\"people2\",text:\"人员管理\",handler:function(item){openMenu(item, '../../sys/emp_forward.action', '人员管理', '');}};\n");
      out.write("\n");
      out.write("\t\tvar menu_reportData = {\n");
      out.write("\t\t\t\t\t\t\tid:\"reportData\",\n");
      out.write("\t\t\t\t\t\t\ttext:\"报表管理\",\n");
      out.write("\t\t\t\t\t\t\thandler:function(item){\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\treturn;openMenu(item, '..', '报表管理', '');\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t,menu: new Ext.menu.Menu({\n");
      out.write("\t\t\t\t\t\t\t\titems: [\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//menu_people2 \n");
      out.write("\t\t\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t};\n");
      out.write("\t\t\n");
      out.write("\t\tvar menu_newsCategory = {id:\"newsCategory\",text:\"新闻类别管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/newsCategory/main', '新闻类别管理', '');}};\n");
      out.write("\n");
      out.write("\t\tvar menu_news = {id:\"news\",text:\"新闻管理\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/news/main', '新闻管理', '');}};\n");
      out.write("\n");
      out.write("\t\tvar menu_newsComments = {id:\"newsComments\",text:\"新闻点评\",handler:function(item){openMenu(item, '");
      out.print(basePath);
      out.write("/newsComments/main', '新闻点评', '');}};\n");
      out.write("\n");
      out.write("\t\tvar menu_newsData = {\n");
      out.write("\t\t\t\t\t\t\tid:\"newsData\",\n");
      out.write("\t\t\t\t\t\t\ttext:\"新闻管理\",\n");
      out.write("\t\t\t\t\t\t\thandler:function(item){\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\treturn;openMenu(item, '..', '新闻管理', '');\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t,menu: new Ext.menu.Menu({\n");
      out.write("\t\t\t\t\t\t\t\titems: [\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmenu_newsCategory\n");
      out.write("\t\t\t\t\t\t\t\t\t\t,menu_news\n");
      out.write("\t\t\t\t\t\t\t\t\t\t,menu_newsComments\n");
      out.write("\t\t\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t};\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\t\tvar menuBar = new Ext.Toolbar({\n");
      out.write("\t\t\t\t\t\t\tenableOverflow:\"true\"\n");
      out.write("\t\t\t\t\t\t\t,items: [\n");
      out.write("\t\t\t\t\t\t\t\t\t\t'-'\t,menu_sysManager,'-',menu_baseData,'-',menu_bizData,'-',menu_orderManager,'-',menu_reportData,'-',menu_newsData,'-','->'\n");
      out.write("\t\t\t\t\t\t\t\t\t\t,{\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ticon:\"");
      out.print(basePath );
      out.write("/assets/images/frame/new.gif\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttext:\"工具\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tcls:\"x-btn-text-icon\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t,menu: new Ext.menu.Menu({\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tshowSeparator:\"false\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t,items: [\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ticon:\"");
      out.print(basePath );
      out.write("/assets/images/frame/home.gif\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttext:\"返回首页\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcls:\"x-btn-text-icon\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thandler:function(){\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttabs.setActiveTab('home');\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,{\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ticon:\"");
      out.print(basePath );
      out.write("/assets/images/frame/close.gif\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttext:\"关闭所有标签页\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcls:\"x-btn-text-icon\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thandler:function(){\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcloseAllTab();\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,{\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ticon:\"");
      out.print(basePath );
      out.write("/assets/images/frame/version.gif\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttext:\"版本信息\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcls:\"x-btn-text-icon\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thandler:function(){\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tversionWin.show();\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,{\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ticon:\"");
      out.print(basePath );
      out.write("/assets/images/frame/user.gif\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttext:\"用户信息\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcls:\"x-btn-text-icon\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thandler:function(){\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tuserWin.show();\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,{\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ticon:\"");
      out.print(basePath );
      out.write("/assets/images/frame/password.gif\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttext:\"修改密码\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcls:\"x-btn-text-icon\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thandler:function(){\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tchangePasswordWin.show();\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,{\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ticon:\"");
      out.print(basePath );
      out.write("/assets/images/frame/exit.gif\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttext:\"退出登录\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcls:\"x-btn-text-icon\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thandler:function(){\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tlogout();\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t' '\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\tvar tabs = new Ext.TabPanel({\n");
      out.write("\t\t\t\t\t\t\t\t\t\tregion:\"center\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\tautoScroll:true,\n");
      out.write("\t\t\t\t\t\t\t\t\t\tactiveItem:\"home\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\tborder:false,\n");
      out.write("\t\t\t\t\t\t\t\t\t\tenableTabScroll:true\n");
      out.write("\t\t\t\t\t\t\t\t\t\t,items: [\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tnew Ext.Panel({id:\"home\",title:\"首页\",layout:\"border\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,items: [\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tnew Ext.Panel({id:\"homemain\",region:\"center\",border:false\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,html: \"\\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t<iframe src=\\'");
      out.print(basePath);
      out.write("/home\\' width=\\'100%\\' height=\\'100%\\' frameborder=\\'0\\'></iframe>\\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\"\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,new Ext.Panel({id:\"homebar\",region:\"north\",cls:\"x-toolbar\",height:25,layout:\"border\",border:false\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,items: [\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tnew Ext.Panel({id:\"homemsg\",region:\"center\",border:false\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,html: \"\\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t<table border=\\'0\\' cellpadding=\\'0\\' cellspacing=\\'0\\' width=\\'100%\\' height=\\\"25\\\" style=\\'background-color: #FFDF8C;\\'><tr><td width=\\'24\\' align=\\'center\\'><img src=\\'");
      out.print(basePath );
      out.write("/assets/images/frame/info.gif\\' border=\\'0\\' height=\\'16\\' width=\\'16\\'/></td><td>XX管理系统demo</td></tr></table>\\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,new Ext.Panel({id:\"homebtn\",region:\"east\",width:22,border:false\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,items: [\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tnew Ext.Button({\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid:\"homehelp\",icon:\"");
      out.print(basePath );
      out.write("/assets/images/frame/help.gif\",cls:\"x-btn-icon\",style:\"background-color: #FFDF8C;\",tooltip:\"帮助\",handler:function() {showHelp('');}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\tvar framePane = new Ext.Viewport({\n");
      out.write("\t\t\t\t\t\t\tlayout:\"border\"\n");
      out.write("\t\t\t\t\t\t\t,items: [\n");
      out.write("\t\t\t\t\t\t\t\t\tnew Ext.Panel({\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttbar:menuBar,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tregion:\"center\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tlayout:\"border\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tborder:false\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t,items: [\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttabs\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\tvar userWin = new Ext.Window({\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle:\"用户信息\",\n");
      out.write("\t\t\t\t\t\t\t\t\theight:200,\n");
      out.write("\t\t\t\t\t\t\t\t\tframe:true,\n");
      out.write("\t\t\t\t\t\t\t\t\twidth:300,\n");
      out.write("\t\t\t\t\t\t\t\t\tlayout:\"border\",\n");
      out.write("\t\t\t\t\t\t\t\t\tcloseAction:\"hide\",\n");
      out.write("\t\t\t\t\t\t\t\t\tmodal:true\n");
      out.write("\t\t\t\t\t\t\t\t\t,items: [\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tnew Ext.Panel({\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tregion:\"center\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tframe:true,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tborder:false\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,html:\"\\r\\n\\t\\t\\t\\t\\t<table border=\\\"0\\\" width=\\\"100%\\\" class=\\\"x-form-field\\\" style=\\\"font-size:15\\\">\"+\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"\\r\\n\\t\\t\\t\\t\\t\\t<tr>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td colspan=\\\"2\\\">&nbsp;</td>\\r\\n\\t\\t\\t\\t\\t\\t</tr>\"+\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"\\r\\n\\t\\t\\t\\t\\t\\t<tr>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td style=\\\"border-bottom:1px dashed #BEBEBE\\\" align=\\\"right\\\" width=\\\"120\\\">用户名&nbsp;:&nbsp;&nbsp;</td>\"+\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"\\r\\n\\t\\t\\t\\t\\t\\t\\t<td style=\\\"border-bottom:1px dashed #BEBEBE\\\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userName}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("</td>\"+\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"\\r\\n\\t\\t\\t\\t\\t\\t\\r\\n\\t\\t\\t\\t\\t</table>\\r\\n\\t\\t\\t\\t\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\tvar versionWin = new Ext.Window({\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle:\"版本信息\",\n");
      out.write("\t\t\t\t\t\t\t\t\theight:330,\n");
      out.write("\t\t\t\t\t\t\t\t\tframe:true,\n");
      out.write("\t\t\t\t\t\t\t\t\twidth:345,\n");
      out.write("\t\t\t\t\t\t\t\t\tlayout:\"border\",\n");
      out.write("\t\t\t\t\t\t\t\t\tcloseAction:\"hide\",\n");
      out.write("\t\t\t\t\t\t\t\t\tmodal:true\n");
      out.write("\t\t\t\t\t\t\t\t\t,items: [\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tnew Ext.Panel({\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tregion:\"center\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tframe:true,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tborder:false\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t,html:\"\\r\\n\\t\\t\\t\\t\\t<table border=\\\"0\\\" class=\\\"x-form-field\\\" style=\\\"font-size:14\\\">\\r\\n\\t\\t\\t\\t\\t\\t<tr>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td colspan=\\\"2\\\"><a href=\\\"http://www.sf-express.com\\\" target=\\\"_blank\\\"><img style=\\\"background-color: black\\\" src=\\\"");
      out.print(basePath );
      out.write("/assets/images/frame/sf_logo.png\\\" alt=\\\"SF-Express\\\"/></a></td>\\r\\n\\t\\t\\t\\t\\t\\t</tr>\\r\\n\\t\\t\\t\\t\\t\\t<tr>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td colspan=\\\"2\\\" style=\\\"font-size:20\\\">XX管理系统demo</td>\\r\\n\\t\\t\\t\\t\\t\\t</tr>\\r\\n\\t\\t\\t\\t\\t\\t<tr>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td colspan=\\\"2\\\"><hr/></td>\\r\\n\\t\\t\\t\\t\\t\\t</tr>\\r\\n\\t\\t\\t\\t\\t\\t<tr>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td align=\\\"right\\\" width=\\\"120\\\">版本类型&nbsp;:&nbsp;&nbsp;</td>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td>生产环境(product)</td>\\r\\n\\t\\t\\t\\t\\t\\t</tr>\\r\\n\\t\\t\\t\\t\\t\\t<tr>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td align=\\\"right\\\">版本号&nbsp;:&nbsp;&nbsp;</td>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td>1.0</td>\\r\\n\\t\\t\\t\\t\\t\\t</tr>\\r\\n\\t\\t\\t\\t\\t\\t<tr>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td align=\\\"right\\\">发布时间&nbsp;:&nbsp;&nbsp;</td>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td>@release.date@</td>\\r\\n\\t\\t\\t\\t\\t\\t</tr>\\r\\n\\t\\t\\t\\t\\t\\t<tr>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td align=\\\"right\\\">Framework&nbsp;:&nbsp;&nbsp;</td>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td>EXT3-MIXROLE</td>\\r\\n\\t\\t\\t\\t\\t\\t</tr>\\t\\t\\t\\t\\t\\t\\r\\n\\t\\t\\t\\t\\t\\t<tr>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td colspan=\\\"2\\\"><hr/></td>\\r\\n\\t\\t\\t\\t\\t\\t</tr>\\r\\n\\t\\t\\t\\t\\t\\t<tr>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td colspan=\\\"2\\\">Copyright (c) 2012, S.F. Express Inc. All rights reserved.</td>\\r\\n\\t\\t\\t\\t\\t\\t</tr>\\r\\n\\t\\t\\t\\t\\t\\t<tr>\\r\\n\\t\\t\\t\\t\\t\\t\\t<td colspan=\\\"2\\\"><br/></td>\\r\\n\\t\\t\\t\\t\\t\\t</tr>\\r\\n\\t\\t\\t\\t\\t</table>\\r\\n\\t\\t\\t\\t\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\tvar oldPasswordVar = new Ext.form.TextField({minLengthText:\"旧密码最小长度为8\",allowBlank:false,maxLength:20,blankText:\"旧密码不能为空\",minLength:6,inputType:\"password\",name:\"oldPassword\",maxLengthText:\"旧密码最大长度为20\",fieldLabel:\"旧密码\"});\n");
      out.write("\n");
      out.write("\t\tvar newPasswordVar = new Ext.form.TextField({minLengthText:\"新密码最小长度为8\",allowBlank:false,maxLength:20,blankText:\"新密码不能为空\",minLength:6,inputType:\"password\",name:\"newPassword\",maxLengthText:\"新密码最大长度为20\",fieldLabel:\"新密码\"});\n");
      out.write("\n");
      out.write("\t\tvar newPasswordConfirmVar = new Ext.form.TextField({minLengthText:\"确认新密码最小长度为8\",allowBlank:false,maxLength:20,blankText:\"确认新密码不能为空\",minLength:6,inputType:\"password\",name:\"newPasswordConfirm\",maxLengthText:\"确认新密码最大长度为20\",fieldLabel:\"确认新密码\"});\n");
      out.write("\n");
      out.write("\t\tvar changePasswordForm = new Ext.form.FormPanel({\n");
      out.write("\t\t\t\t\t\t\t\t\t\tregion:\"center\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\tframe:true,\n");
      out.write("\t\t\t\t\t\t\t\t\t\tborder:false\n");
      out.write("\t\t\t\t\t\t\t\t\t\t,items: [\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\toldPasswordVar\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t,newPasswordVar\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t,newPasswordConfirmVar\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\tvar changePasswordWin = new Ext.Window({\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle:\"修改密码\",\n");
      out.write("\t\t\t\t\t\t\t\t\theight:240,\n");
      out.write("\t\t\t\t\t\t\t\t\tframe:true,\n");
      out.write("\t\t\t\t\t\t\t\t\twidth:300,\n");
      out.write("\t\t\t\t\t\t\t\t\tlayout:\"border\",\n");
      out.write("\t\t\t\t\t\t\t\t\tcloseAction:\"hide\",\n");
      out.write("\t\t\t\t\t\t\t\t\tmodal:true\n");
      out.write("\t\t\t\t\t\t\t\t\t,items: [\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tnew Ext.Panel({\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tregion:\"center\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tlayout:\"border\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tborder:false\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t,tbar: [\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tnew Ext.Button({text:\"保存\",cls:\"x-btn-normal\",handler:saveChangePwd\t})\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t,new Ext.Button({text:\"重置\",cls:\"x-btn-normal\",handler:function() {changePasswordForm.getForm().reset();}\t})\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t,items: [\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tchangePasswordForm\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t\t\t\t});\n");
      out.write("\t\tchangePasswordForm.savePassword = function() {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tchangePasswordForm.getForm().doAction(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'submit',\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfailure:changePasswordFailure,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsuccess:changePasswordSuccess,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\turl:\"");
      out.print(basePath );
      out.write("/user/changPassword\"});\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t    function saveChangePwd() {\n");
      out.write("\t\t\t\t\t\tif(changePasswordForm.getForm().isValid()) {\n");
      out.write("\t\t\t\t\t\t\tvar oldPasswordVarValue = oldPasswordVar.getValue();\n");
      out.write("\t\t\t\t\t\t\tvar newPasswordVarValue = newPasswordVar.getValue();\n");
      out.write("\t\t\t\t\t\t\tvar newPasswordConfirmVarValue = newPasswordConfirmVar.getValue();\n");
      out.write("\t\t\t\t\t\t\tif (validatePassword(oldPasswordVarValue, newPasswordVarValue, newPasswordConfirmVarValue))\n");
      out.write("\t\t\t\t\t\t\t\tchangePasswordForm.savePassword();\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t    }\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t// 检验密码表单数据\n");
      out.write("\n");
      out.write("\t\t\tfunction validatePassword(oldPasswordVarValue, newPasswordVarValue, newPasswordConfirmVarValue) {\n");
      out.write("\t\t\t\tif(! checkPassword(oldPasswordVarValue, '旧密码')) {\n");
      out.write("\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tif(! checkPassword(newPasswordVarValue, '新密码')) {\n");
      out.write("\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tif(! checkPassword(newPasswordConfirmVarValue, '确认新密码')) {\n");
      out.write("\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tif(oldPasswordVarValue == newPasswordVarValue){\n");
      out.write("\t\t\t\t\tExt.MessageBox.alert('提示', '新密码不能与旧密码相同!');\n");
      out.write("\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tif(newPasswordVarValue != newPasswordConfirmVarValue) {\n");
      out.write("\t\t\t\t\tExt.MessageBox.alert('提示', '确认新密码与新密码不一致!');\n");
      out.write("\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\treturn true;\n");
      out.write("\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t// 检验密码，包括长度为八位，必需为数字与字母混合等\n");
      out.write("\t\t\tfunction checkPassword(password, name) {\n");
      out.write("\t\t\t    if(password == null || password == ''){\n");
      out.write("\t\t\t        Ext.MessageBox.alert('提示', name + '不能为空');\n");
      out.write("\t\t\t        return false;\n");
      out.write("\t\t\t    }\n");
      out.write("\t\t\t    if(password.length < 8){\n");
      out.write("\t\t\t        Ext.MessageBox.alert('提示', name + '长度必须大于八位');\n");
      out.write("\t\t\t        return false;\n");
      out.write("\t\t\t    }\n");
      out.write("\t\t        var pwdPtn = /^[\\x21-\\x7e]*$/;\n");
      out.write("\t\t       \tif(!pwdPtn.test(password)){\n");
      out.write("\t\t       \t    Ext.MessageBox.alert('提示', name + '必须由英文字母、数字和特殊字符组成，必须同时包含字母和数字');\n");
      out.write("\t\t       \t    return false;\n");
      out.write("\t\t       \t}\n");
      out.write("\n");
      out.write("\t\t\t    //判断是否数字和英文组成\n");
      out.write("\t\t\t    var numFlag = false;\n");
      out.write("\t\t\t    var charFlag = false;\n");
      out.write("\t\t\t    for(var i =0; i < password.length; i++){\n");
      out.write("\t\t\t        if(password.charAt(i) >= '0' && password.charAt(i) <= '9'){\n");
      out.write("\t\t\t            numFlag = true;\n");
      out.write("\t\t\t        }\n");
      out.write("\t\t\t        if( ( password.charAt(i) >= 'A' && password.charAt(i) <= 'Z' ) || ( password.charAt(i) >= 'a' && password.charAt(i) <= 'z' )){\n");
      out.write("\t\t\t            charFlag = true;\n");
      out.write("\t\t\t        }\n");
      out.write("\t\t\t    }\n");
      out.write("\t\t\t    if(! charFlag || ! numFlag ) {\n");
      out.write("\t\t\t        Ext.MessageBox.alert('提示', name + '必须由英文字母、数字和特殊字符组成，必须同时包含字母和数字');\n");
      out.write("\t\t\t\t\treturn false;\n");
      out.write("\t\t\t    }\n");
      out.write("\t\t\t    return true;\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\tfunction changePasswordSuccess(form, action) {\n");
      out.write("\t\t\t\tif (action.result.msg) {\n");
      out.write("\t\t\t\t\tExt.Msg.alert(\"提示\",action.result.msg);\n");
      out.write("\t\t\t\t} else {\n");
      out.write("\t\t\t\t\tchangePasswordWin.hide();\n");
      out.write("\t\t\t\t\tchangePasswordForm.getForm().reset();\n");
      out.write("\t\t\t\t\tExt.MessageBox.alert(\"成功\", \"修改密码成功,将在您下一次登录时生效!\");\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\tfunction changePasswordFailure(form, action) {\n");
      out.write("\t\t\t\tvar msg = '';\n");
      out.write("\t\t\t\tif (action && action.result && action.result.error) {\n");
      out.write("\t\t\t\t\tExt.Msg.alert(\"提示\",\"系统出现了异常,请与管理员联系!\");\n");
      out.write("\t\t\t\t} else {\n");
      out.write("\t\t\t\t\tif (action.failureType === Ext.form.Action.CONNECT_FAILURE) {\n");
      out.write("\t\t\t\t\t\tif (action.response.status == 0) {\n");
      out.write("\t\t\t\t\t\t\tmsg = \"连接失败,无法连接到服务器!\";\n");
      out.write("\t\t\t\t\t\t} else if (action.response.status == -1) {\n");
      out.write("\t\t\t\t\t\t\tmsg = \"服务器处理超时!\";\n");
      out.write("\t\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\t\tmsg = String.format(\"错误代码:{0}, 错误描述:{1}!\",action.response.status,action.response.statusText);\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t} else if (action.failureType === Ext.form.Action.CLIENT_INVALID) {\n");
      out.write("\t\t\t\t\t\tmsg = \"请将表单填写正确!\";\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\tExt.Msg.alert(\"提示\", msg);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t    function closeAllTab() {\n");
      out.write("\t\t        var ts = tabs.findBy(function() {\n");
      out.write("\t\t            if (this.id != 'home' \n");
      out.write("\t\t                && this.id != 'homemain' \n");
      out.write("\t\t                && this.id != 'homemain' \n");
      out.write("\t\t                && this.id != 'homebar' \n");
      out.write("\t\t                && this.id != 'homemsg'\n");
      out.write("\t\t                && this.id != 'homebtn' \n");
      out.write("\t\t                && this.id != 'homehelp') {\n");
      out.write("\t\t                return true;\n");
      out.write("\t\t            }\n");
      out.write("\t\t        });\n");
      out.write("\n");
      out.write("\t\t        for (i = 0; i < ts.length; i++) {\n");
      out.write("\t\t            tabs.remove(ts[i]);\n");
      out.write("\t\t        }\n");
      out.write("\t\t    }\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\tfunction showHelp(helpUrl) {\n");
      out.write("\t\t\t\tif (helpUrl && helpUrl.length > 0) {\n");
      out.write("\t\t\t\t\twindow.open('' + helpUrl, '_blank', 'height=600,width=800,resizable=yes,scrollbars=yes');\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\tfunction logoutConfirmed(s) {\n");
      out.write("\t\t\t\tif (s == 'yes') {\n");
      out.write("\t\t\t\t\twindow.location.href='");
      out.print(basePath );
      out.write("/login/logout';\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\tfunction logout() {\n");
      out.write("\t\t\t\tExt.MessageBox.confirm(\"退出登录\", \"确定退出登录?&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\", logoutConfirmed);\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\tfunction openMenu(item, url, desc, helpUrl) {\n");
      out.write("\t\t\t    if(url != null && url != ''){\n");
      out.write("\t\t\t\t\topenPage(item.id, item.text, desc, helpUrl, url, true);\n");
      out.write("\t\t\t    }\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\tfunction openTab(id, text, desc, helpUrl, url) {\n");
      out.write("\t\t\t\tif(url != null && url != ''){\n");
      out.write("\t\t\t\t\topenPage(id, text, desc, helpUrl, url, true);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\tfunction refreshTab(id, text, desc, helpUrl, url) {\n");
      out.write("\t\t\t\trefreshPage(id, text, desc, helpUrl, url, true);\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\tfunction openPage(id, text, desc, helpUrl, url, closable) {\n");
      out.write("\t\t\t\tvar tab = tabs.getItem(id);\n");
      out.write("\t\t\t\tif (typeof(tab) == \"undefined\" || tab == null) {\n");
      out.write("\t\t\t\t\ttabs.add(createTabPane(id, text, desc, helpUrl, url, closable)).show();\n");
      out.write("\t\t        } else {\n");
      out.write("\t\t        \ttabs.setActiveTab(tab);\n");
      out.write("\t\t        }\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\tfunction refreshPage(id, text, desc, helpUrl, url, closable) {\n");
      out.write("\t\t\t\tvar tab = tabs.getItem(id);\n");
      out.write("\t\t\t\tif (typeof(tab) != \"undefined\" && tab != null) {\n");
      out.write("\t\t\t\t\ttabs.remove(tab);\n");
      out.write("\t\t        }\n");
      out.write("\t\t        tabs.add(createTabPane(id, text, desc, helpUrl, url, closable)).show();\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\tfunction createTabPane(id, text, desc, helpUrl, url, closable) {\n");
      out.write("\t\t\t\tvar tabPane = new Ext.Panel({\n");
      out.write("\t\t\t\t\t\tid: id,\n");
      out.write("\t\t\t\t\t\ttitle: text,\n");
      out.write("\t\t\t\t\t\tborder: false,\n");
      out.write("\t\t\t\t\t\tclosable: closable,\n");
      out.write("\t\t\t\t\t\tlayout: \"border\",\n");
      out.write("\t\t\t\t\t\titems: [\n");
      out.write("\t\t\t\t\t\t\tnew Ext.Panel({\n");
      out.write("\t\t\t\t\t\t\t\tregion: \"north\",\n");
      out.write("\t\t\t\t\t\t\t\tcls: \"x-toolbar\",\n");
      out.write("\t\t\t\t\t\t\t\theight: 25,\n");
      out.write("\t\t\t\t\t\t\t\tborder: false,\n");
      out.write("\t\t\t\t\t\t\t\tlayout: \"border\",\n");
      out.write("\t\t\t\t\t\t\t\titems: [\n");
      out.write("\t\t\t\t\t\t\t\t\tnew Ext.Panel({\n");
      out.write("\t\t\t\t\t\t\t\t\t\tregion: \"east\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth: 44,\n");
      out.write("\t\t\t\t\t\t\t\t\t\tborder: false,\n");
      out.write("\t\t\t\t\t\t\t\t\t\tlayout: \"border\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\titems: [\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tnew Ext.Panel({\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tregion: \"west\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\twidth: 22,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tborder: false,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tlayout: \"form\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\titems: [\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tnew Ext.Button({\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tcls: \"x-btn-icon\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ticon: \"");
      out.print(basePath );
      out.write("/assets/images/frame/new.gif\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ttooltip: \"在新的标签页中打开\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle: \"background-color: #FFDF8C;\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\thandler: function(){openPage(id + '1', text, desc, helpUrl, url, closable);}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}),\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tnew Ext.Panel({\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tregion: \"center\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tborder: false,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tlayout: \"form\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\titems: [\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tnew Ext.Button({\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tcls: \"x-btn-icon\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ticon: \"");
      out.print(basePath );
      out.write("/assets/images/frame/help.gif\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ttooltip: \"帮助\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle: \"background-color: #FFDF8C;\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\thandler: function(){showHelp(helpUrl);}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t\t\t\t}),\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\tnew Ext.Panel({\n");
      out.write("\t\t\t\t\t\t\t\t\t\tregion: \"center\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\tborder: false,\n");
      out.write("\t\t\t\t\t            \t\thtml: \"<table border='0' cellpadding='0' cellspacing='0' width='100%' height='25' style='background-color: #FFDF8C;'><tr><td width='24' align='center'><img src='");
      out.print(basePath );
      out.write("/assets/images/frame/info.gif' border='0' height='16' width='16'/></td><td>\" + desc + \"</td></tr></table>\"\n");
      out.write("\n");
      out.write("\t\t\t\t\t        \t\t})\n");
      out.write("\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t        }),\n");
      out.write("\n");
      out.write("\t\t\t\t\t        new Ext.Panel({\n");
      out.write("\t\t\t\t\t\t\t\tregion: \"center\",\n");
      out.write("\t\t\t\t\t\t\t\tborder: false,\n");
      out.write("\t\t\t\t\t            html: \"<iframe name='frame_\" + id + \"' src='\" + url + \"' width='100%' height='100%' frameborder='0'></iframe>\"\n");
      out.write("\t\t\t\t\t        })\n");
      out.write("\t\t\t        \t]\n");
      out.write("\t\t\t        });\n");
      out.write("\t\t\t\treturn tabPane;\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\tvar mask = null;\n");
      out.write("\n");
      out.write("\t\t\t// 传入的参数为不被遮罩的元素\n");
      out.write("\n");
      out.write("\t\t\tfunction showModal(win) {\n");
      out.write("\t\t\t\tif (mask == null) {\n");
      out.write("\t\t\t\t\tif (win && win.el && win.el.dom) {\n");
      out.write("\t\t\t\t\t\tmask = framePane.container.createChild({cls:\"ext-el-mask\"}, win.el.dom);\n");
      out.write("\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\tuserWin.show();\n");
      out.write("\t\t\t\t\t\tuserWin.hide();\n");
      out.write("\t\t\t\t\t\tmask = framePane.container.createChild({cls:\"ext-el-mask\"}, userWin.el.dom);\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tExt.getBody().addClass(\"x-body-masked\");\n");
      out.write("\t\t\t\tmask.setSize(Ext.lib.Dom.getViewWidth(true), Ext.lib.Dom.getViewHeight(true));\n");
      out.write("\t\t\t\tmask.show();\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\tfunction hideModal() {\n");
      out.write("\t\t\t\tmask.hide();\n");
      out.write("\t\t\t\tExt.getBody().removeClass(\"x-body-masked\");\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\tfunction requestBlank() {\n");
      out.write("\t\t\t\tExt.Ajax.request({\n");
      out.write("\t\t\t\t\turl: 'blank.action',\n");
      out.write("\t\t\t\t\tmethod: 'GET',\n");
      out.write("\t\t\t\t\tdisableCaching: true,\n");
      out.write("\t\t\t\t\tsuccess: function (result, request) {\n");
      out.write("\t\t\t\t\t\tif (result.responseText.indexOf('okokokokokok') == -1) {\n");
      out.write("\t\t\t\t\t\t\twindow.location.href='logout.action';\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\ttry{\n");
      out.write("\n");
      out.write("\t\t\t\tsetInterval(\"requestBlank()\", 1801000);\n");
      out.write("\n");
      out.write("\t\t\t} catch(e) {\n");
      out.write("\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("</script><style type=\"text/css\"></style>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
